### ISSUE TITLE
Le carrousel ne tourne pas ...

### ISSUE THREAD

**Issue by TheBarbe** [sebabouche/airdetox#111]
Seb,

en fait le carrousel ne tourne pas seul... du coup on est figé sur la page du 5h du mat...

Tu en penses quoi?

Tu peux le fixer à 5 sec. / slide stp ?

Merci poto !

**Comment by sebabouche** [comment]
Normalement il tourne (chez moi il tourne). C'est quand la souris est sur une surface actionnable que ça s'arrête.
