### ISSUE TITLE
Escale dépubliée non visible

### ISSUE THREAD

**Issue by actosdu** [sebabouche/airdetox#118]
Les escales dépubliées ne sont plus visibles sur le plan de vol... Où peut-on retrouver les infos ?

![capture d ecran 2015-01-27 a 13 38 03](https://cloud.githubusercontent.com/assets/9965964/5918537/1cd8405a-a62a-11e4-834b-3f3031893cf6.png)

**Comment by sebabouche** [comment]
Dans la base de donnée.

**Comment by sebabouche** [comment]
Ok ce sera bon au prochain upload / cacheclear
