### ISSUE TITLE
Bouton "CheckIn" dans l'édition du ticket

### ISSUE THREAD

**Issue by TheBarbe** [sebabouche/airdetox#128]
Le bouton n'apparait pas...

![screen shot 2015-01-30 at 11 18 31](https://cloud.githubusercontent.com/assets/1126057/5974196/c6570d52-a871-11e4-918a-fa22ebe44a53.png)

**Comment by TheBarbe** [comment]
En fait c'est simplement due à l'absence de lien url dans le back end.. c'est bien ça?

**Comment by sebabouche** [comment]
Done.
