### ISSUE TITLE
Bouton "Laisser une évaluation" ne fonctionne pas

### ISSUE THREAD

**Issue by TheBarbe** [sebabouche/airdetox#132]
redirection direct 404 sur la page Mon AIRDETOX

**Comment by sebabouche** [comment]
Oui c'est parce que les gens doivent remplir leur extended profile avant. Mais on le message n'apparait qu'en app_dev.php ce qui n'est pas très courteois.

**Comment by sebabouche** [comment]
Je vais corriger ça.

**Comment by sebabouche** [comment]
C'est bueno. J'ai collé un modal avant qui dit de remplir son profil.

**Comment by actosdu** [comment]
![capture d ecran 2015-02-03 a 12 57 50](https://cloud.githubusercontent.com/assets/9965964/6019760/65240e6e-aba4-11e4-9691-961d3d0610ee.png)

**Comment by TheBarbe** [comment]
Ce que veut dire annecha, c'est qu'elle a rempli tout son profil et que ça ne marche toujours pas.
Idéalement, il faudrait pouvoir laisser un témoignage sans obligation de remplir tout son profil.
ça te va ?

**Comment by sebabouche** [comment]
Non, c'est bien de pousser à la création de profil.

**Comment by sebabouche** [comment]
Ressayez.
