### ISSUE TITLE
Création passeport user

### ISSUE THREAD

**Issue by actosdu** [sebabouche/airdetox#94]
Impossible de créer/modifier le passeport d'un user (alors que j'ai réussi à en modifiant un avant), ça me bascule sur le mien par défaut en me disant que je ne peux pas créer 2 passeports... En mode admin et en app_dev.
![capture d ecran 2015-01-07 a 18 29 07](https://cloud.githubusercontent.com/assets/9965964/5650110/a8303b42-969b-11e4-952b-2ddc2e7de5df.png)
![capture d ecran 2015-01-07 a 18 28 52](https://cloud.githubusercontent.com/assets/9965964/5650117/b20440b4-969b-11e4-8b58-193862f50b91.png)

**Comment by sebabouche** [comment]
Tiens, tiens… Je vais regarder ça.
