### ISSUE TITLE
escales dépubliées s'affichant encore - plan de vol clope

### ISSUE THREAD

**Issue by actosdu** [sebabouche/airdetox#95]
![capture d ecran 2015-01-12 a 14 37 02](https://cloud.githubusercontent.com/assets/9965964/5703560/8e7356dc-9a68-11e4-8d57-ac91711ec410.png)
![capture d ecran 2015-01-12 a 14 38 56](https://cloud.githubusercontent.com/assets/9965964/5703585/c55222e6-9a68-11e4-8a9d-0faf677369b8.png)

**Comment by sebabouche** [comment]
Ok ce sera réglé à la prochaine update.
