### ISSUE TITLE
Bug numéro de vol clope 

### ISSUE THREAD

**Issue by actosdu** [sebabouche/airdetox#96]
Création d'un nouveau vol clope pour février mais il vient de se créer avec le numéro 1 et les 7 anciens s'affichent, peuvent être réservés alors qu'ils ne devraient plus s'afficher. Impossible de les dépublier...

**Comment by sebabouche** [comment]
C'est impossible qu'il écrase un vol existant. C'est une modification du vol 1 existant.

**Comment by sebabouche** [comment]
Il faut le remettre aux anciennes dates et il disparaîtra. Et en créer un nouveau (j'ai fait le test ça fonctionne).
