### ISSUE TITLE
Bug partenaire sur vol

### ISSUE THREAD

**Issue by actosdu** [sebabouche/airdetox#97]
Impossible de décaler un vol - le champ partenaire est obligatoire pour valider mais impossible d'écrire ou d'inclure quoique ce soit.
![capture d ecran 2015-01-13 a 13 53 28](https://cloud.githubusercontent.com/assets/9965964/5720964/c51ddf72-9b2b-11e4-9a76-f11a203dcc4b.png)

**Comment by sebabouche** [comment]
Jobzdone
